//Module imports
import react from "react";

//Stylesheet
import '../../Styles/VisionAndGoal.css';

const VisionAndGoal: React.FC = () => {
    return (
        <div className={"ComponentBody"}>
            <div className={"Headline"}>
                <h1>
                    About Us!
                </h1>
                <p>Last edited: 26.06.2024</p>
            </div>
            <p className={"paragraph"}>
                I want to create a website where people can make predictions about how their game of league of legends
                will go. The prediction made works like a bingo card, and the fields can either be generated by the
                website or made by the user. In addition to the predictions part, the website will include a page that
                Haakon can use when he does his regular profile reviews.
            </p>
        </div>
    );
}

export default VisionAndGoal;